### ISSUE TITLE
Add haplogroup-specific allele frequencies

### ISSUE THREAD

**Issue by robertopreste** [mitoNGS/mtoolnote#4]
Need to insert an additional table to the database with haplogroup-specific allele frequencies, and add these data to the annotations provided.

**Comment by robertopreste** [comment]
@clody23 do we need distinct healthy/patient values?

**Comment by clody23** [comment]
@robertopreste I would suggest to provide per-haplogroup allele frequencies calculated only within *healthy* individuals. How many of those we have?

**Comment by robertopreste** [comment]
25 macro-haplogroups (as per [PhyloTree](http://www.phylotree.org/tree/index.htm) classification).
